### ISSUE TITLE
大帝挑战对种族未公开的处理不妥当

### ISSUE THREAD

**Issue by Initial-heart-1** [AmiyaBot/Amiya-Bot-plugins#16]
### 问题描述

小莫和年算作了同一种族，因为都是未公开
震撼我一整年啊一整年
![截图](https://github.com/AmiyaBot/Amiya-Bot/assets/63091661/a39eedee-320e-4a71-ab09-1547fe11f3ba)

### 复现

抽到了谜底是种族未公开的干员即可复现

### Amiya-Bot 版本

主分支 commit 3295a2a

### 其他插件版本

无

### 日志

```text
这不用日志
```

### 补充信息

上文已描述详尽

**Comment by vivien8261** [comment]
可以增加一个 `无法揭示的` 属性，对应所有词条的 unknown 情况

**Comment by Initial-heart-1** [comment]
> 可以增加一个 `无法揭示的` 属性，对应所有词条的 unknown 情况

部分情况也不一定是完全无法揭示的，这个可能还得具体情况具体分析......裂
