### ISSUE TITLE
百度云识别失败

### ISSUE THREAD

**Issue by Sduck-Inverse** [AmiyaBot/Amiya-Bot-plugins#25]
虽然用的是CQHTTP也不行，识别不了公招

**Comment by Sduck-Inverse** [comment]
![0O}BLU~O0YZMRO%TI9E1$5O](https://github.com/AmiyaBot/Amiya-Bot-plugins/assets/87361258/857702c3-d347-48a5-9223-9394f0349cb4)
补图

**Comment by vivien8261** [comment]
CQ的问题已修复，百度云这个疑似你本地代理的问题。
